version: '3'

services:
  notebook:
    container_name: python_notebook
    labels:
      name: jupyter notebook 
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    build: .